### PR TITLE
Migrate to Xcode9.3 (Swift 4.1)

### PR DESCRIPTION
**Pull request by rikusouda**
* Fix bug of ColorPicker (It was not worked)
* Remove warnings ( One warning has remained... )
* Apply recommend settings by Xcode 9.3

If this PR is merged, could you bump the version?

### CODE REVIEW

**Comment by apparition47** [comment]
I noticed you bumped the Swift Version from 3 to 4.0. Do you recommend that the `.swift-version` file be bumped too? Maybe it's a Cocoapod thing though -- you seem to prefer Carthage, I noticed.

**Comment by apparition47** [comment]
Verified working on xcode 9.3. Thanks for the PR!

**Comment by rikusouda** [comment]
Thanks for verifying!

I made sure about CocoaPods. It seems to be no problem, however I updated `.swift-version`.

**Comment by apparition47** [comment]
Thanks as always!

**Pull request merged**
