### PR TITLE
Disable last arrow when flat style #7

### PR DESCRIPTION
**Pull request by rikusouda**
disabled_arrow_flatstyle

Removed last arrow in `flatStyle` case.

@apparition47 
In `flatStyle` case, I think last arrow is unnecessary. So, I don't provide an option. What do you think?

### CODE REVIEW

**Comment by apparition47** [comment]
>In flatStyle case, I think last arrow is unnecessary. So, I don't provide an option. What do you think?

I agree. I think that's a sensible default from the other breadcrumb navs I've seen around different webpages.

**Comment by apparition47** [comment]
Works great!


Unrelated but one thing I missed on the last PR  in `BreadCrumb.swift:385`:
```swift
// @IBInspectable public var animationSpeed: Double = 0.2
let enabledAnimation = !refresh && (self.animationSpeed > 1e-15)
```
I think `Double.leastNonzeroMagnitude` here makes more sense instead of a `1e-15`? I think even a `0` would work in this case since we're comparing `Double` and not integers.

**Comment by rikusouda** [comment]
> I think Double.leastNonzeroMagnitude here makes more sense instead of a 1e-15? I think even a 0 would work in this case since we're comparing Double and not integers.

I see. I changed it zero.

**Comment by rikusouda** [comment]
Thanks!

**Pull request merged**
